# Generated by Django 4.2.23 on 2026-03-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
