# Generated by Django 4.2.29 on 2026-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_swimlane_task_swimlane'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimlane',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
