# Generated by Django 4.2.29 on 2026-03-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_swimlane_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimlane',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
