# Generated by Django 4.2.29 on 2026-04-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_swimlane_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='column',
            name='header_color',
            field=models.CharField(default='#c7ddff', max_length=7),
        ),
    ]
