# Generated by Django 4.2.29 on 2026-04-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_column_bg_color_column_header_color'),
        ('kanban', '0006_task_assignees'),
    ]

    operations = [
    ]
