# Generated by Django 4.2.23 on 2026-04-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_merge_20260401_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimlane',
            name='color',
            field=models.CharField(default='#f1f5f9', max_length=7),
        ),
    ]
