# Generated by Django 4.2.29 on 2026-04-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0011_task_is_completed_subtask'),
        ('kanban', '0011_task_parent'),
    ]

    operations = [
    ]
