# Generated by Django 4.2.29 on 2026-04-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_merge_0011_task_is_completed_subtask_0011_task_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
    ]
