# Generated by Django 4.2.29 on 2026-05-15 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_remove_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='current_column_entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TaskColumnTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.column')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_times', to='kanban.task')),
            ],
            options={
                'unique_together': {('task', 'column')},
            },
        ),
    ]
