# Generated by Django 4.2.29 on 2026-06-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0016_alter_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='swimlane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.swimlane'),
            preserve_default=False,
        ),
    ]
