# Generated by Django 4.2.23 on 2026-06-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0018_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
