# Generated by Django 4.2.29 on 2026-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0021_alter_column_board_alter_column_title_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='swimlane',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_swimlane_per_board'),
        ),
    ]
