# Generated by Django 4.2.29 on 2026-06-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0022_swimlane_unique_swimlane_per_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
    ]
